version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    container_name: auto-vs-uuid
    environment:
      MYSQL_DATABASE: auto-vs-uuid
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13312:3306"
